theme: jekyll-theme-minimal
title: Home Test Ada Lookingfor1
description: A template website for ADA Lookingfor1
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
